name: Create Feedback

on:
  workflow_dispatch:
    inputs:
      feedback_text:
        description: 'Feedback text provided by the user'
        required: true
        type: string

jobs:
  create_feedback:
    runs-on: ubuntu-latest

    steps:
      - name: Generate feedback file
        run: |
          RANDOM_ID=$(openssl rand -hex 6)
          FILE_PATH="feedback/$RANDOM_ID.md"
          
          # Create the feedback directory if it doesn't exist
          mkdir -p feedback
          
          echo "# User Feedback" >> $FILE_PATH
          echo "${{ github.event.inputs.feedback_text }}" >> $FILE_PATH
          
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add $FILE_PATH
          git commit -m "Added feedback $RANDOM_ID"
          git push
